name: Prod
variables:
  - name: email
    value: support@oktopus.app.br
  - secret: true
    name: password
  - name: device
    value: 708190328310CPD
  - name: url
    value: https://app.oktopus.app.br/api/
  - name: base_url
    value: https://app.oktopus.app.br/api/
  - secret: true
    name: upload_file_username
  - secret: true
    name: upload_file_password
  - secret: true
    name: download_file_username
  - secret: true
    name: download_file_password
  - name: base_url_ws
    value: ""
  - name: base_url_speedtest_server
    value: ""
