name: Prod
variables:
  - name: email
    value: youremail@email
  - secret: true
    name: password
  - name: device
    value: device-id
  - name: url
    value: https://{domain-name}/api/
  - name: base_url
    value: https://{domain-name}/api/
  - secret: true
    name: upload_file_username
  - secret: true
    name: upload_file_password
  - secret: true
    name: download_file_username
  - secret: true
    name: download_file_password
  - name: base_url_ws
    value: ""
  - name: base_url_speedtest_server
    value: ""
